name: MkDocs documentation
on:
  push:
    branches:
      - mkdocs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mkdocs
      - name: Build documentation
        run: |
          python docs/autogen.py
          ls -al docs/sources
      - name: Upload documentation to gh-pages branch
        run: mkdocs gh-deploy -f docs/mkdocs.yml -c -v --force
      - name: Deploy gh-pages as GitHub Pages website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/sources