name: MkDocs documentation
on:
  push:
    branches:
      - mkdocs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install MkDocs
        run: pip install mkdocs
      - name: Make site directory
        run: mkdir sources
      - name: Build documentation
        run: |
          mkdocs build -f docs/mkdocs.yml -d sources -c -v
          ls -al sources
      - name: Deploy documentation
        run: mkdocs gh-deploy -f docs/mkdocs.yml -c -v --force